### ISSUE TITLE
[macOS] unzipped files missing metadata

### ISSUE THREAD

**Issue by JDLogic** [MinecraftForge/JavaWrapper#6]
The runtime JRE cannot be run from within the "Application Support" folder due to the default permissions on that folder. This was tested using a newly created user on macOS 10.12 .

It sounds like to goal of #2 is to eventually package this in a ".app" container for use on macOS. If this is the case, then I would suggest storing the runtime JRE in the app container (once that is done) as that is what Mojang's official Minecraft.app currently does.

BTW, the this starts the minecraft launcher just fine on mac when using the system JRE.

**Comment by 0xilly** [comment]
We can't package the JRE for filesize reasons what I could do is shortcut the issue by moving the download location but I don't like that idea much either

**Comment by JDLogic** [comment]
Sorry, I did not mean to imply packaging the JRE itself. What I meant was to eventually change the download location to be inside an app container as it can be used as a folder. This would solve the permission problem and keep it in a safe, reliable location.

**Comment by 0xilly** [comment]
Cool just need to figure out how to bundle it then.

**Comment by 0xilly** [comment]
@JDLogic could you post the error as well or a screenshot (I still need to write a logger)

**Comment by JDLogic** [comment]
Runtime JRE (fails):
<img width="725" alt="forgewrapper runtime jre" src="https://cloud.githubusercontent.com/assets/6103327/20700405/164c45b6-b5c2-11e6-8d43-97bd1dd43cd4.png">
^ The last two commands are manual attempts at using the runtime JRE. There is no actual errors from the JavaWrapper, it just quits quietly without starting the launcher.

System JRE (runs):
<img width="585" alt="forgewrapper system jre" src="https://cloud.githubusercontent.com/assets/6103327/20700426/371829e0-b5c2-11e6-86af-b0149be99394.png">

**Comment by 0xilly** [comment]
could you try setting the permissions for the runtime directory `chmod -R +rw ~/Library/Application Support/minecraft/runtime`

**Comment by JDLogic** [comment]
I have to apologize as my initial assumption of it being a permissions problem (based on the error) was not correct. After lots of testing, I realized the real problem was staring me in the face the whole time.
<img width="528" alt="unzip example" src="https://cloud.githubusercontent.com/assets/6103327/20739618/2dd45a70-b671-11e6-8ff2-ae4ec4fc0a0a.png">
^ On the left is the file created by the wrapper and on the right is the file created by manually extracting the JRE zip. The real problem is the unzip function does not fully work on macs as some of the file metadata is lost in the process. Now I have to honest in that I really do not know what causes this or how to fix it. The only solution I have found is to use the built in system utility for extracting archives, which can be invoked with the following command:
`ditto -xk path/to/file.zip path/to/destination`
Hope this helps.

**Comment by 0xilly** [comment]
ok I just have to rewrite the unzip function.

**Comment by 0xilly** [comment]
Try this branch please https://github.com/MinecraftForge/JavaWrapper/tree/osxfix

**Comment by 0xilly** [comment]
@JDLogic try this build https://github.com/MinecraftForge/JavaWrapper/releases/tag/v0.0.1c-alpha

**Comment by JDLogic** [comment]
Sadly, it looks like the changes did not solve the issue. The unzipped files still loose their file type info. Also, if the minecraft directory does not exist, then the wrapper errors when it tries to download the launcher package as the destination does not exist.

**Comment by 0xilly** [comment]
@JDLogic ok did a little bit of a hammer meets nail solution but it should work... I hope this works https://github.com/MinecraftForge/JavaWrapper/releases/tag/v0.0.2b-alpha also fixed the .minecraft check

**Comment by 0xilly** [comment]
wait that one is broken give me a sec an ill fix it

**Comment by 0xilly** [comment]
https://github.com/MinecraftForge/JavaWrapper/releases/tag/v0.0.2c-alpha

**Comment by JDLogic** [comment]
It works! Everything seems to run fine now as intended.
