### ISSUE TITLE
Java search is limited

### ISSUE THREAD

**Issue by vandench** [MinecraftForge/JavaWrapper#8]
When the executable runs it identifies that a version of java exists in the default location (`/usr/bin/java`) but does not check `JAVA_HOME` for the path of the JRE being used. ~~The program also continued to download a copy of the JRE (with the same version as the one in `/usr/bin/java` (`1.8.0_74`)) to the minecraft runtime folder (`~/Library/Application Support/minecraft/runtime/`).~~ Also it appears that this program does not support the [new launcher](https://www.reddit.com/r/Minecraft/comments/59b7m0/help_us_test_the_new_minecraft_launcher_check_the/). Before launching the mc launcher it mentions that it will be using the `system JRE` which seems like a mistake in the message or not a mistake and an overly redundant JRE download, the exact message is `ForgeWrapper is now lauching the laucnher with system JRE` (the word launch also needs to be fixed).

**Comment by vandench** [comment]
The redundant downloading of the JRE is fixed in the release `JavaWrapper-0.0.2c-darwin-amd64`.

**Comment by 0xilly** [comment]
Right now we are kinda supporting the new launcher. Look at the running program look at the title bar aside from that im not sure what I could to support it native applications. Spelling is easily fixed :D ill fix that in the next alpha.

**Comment by 0xilly** [comment]
right now the java check works by executing a [LookPath](https://golang.org/pkg/os/exec/#LookPath) [here](https://github.com/MinecraftForge/JavaWrapper/blob/master/util/javahelper.go#L29-L39) I could do a special check for `JAVA_HOME` but I think that's a little much what do you think @LexManos ?

**Comment by vandench** [comment]
The reason I mention `JAVA_HOME` (or sometimes `JRE_HOME`) is because I personally don't have administrator access on my mac, so the version of java is rarely updated, but I did figure out how to decompress the java installer and set `JAVA_HOME` to it's location (and `JRE_HOME` to `JAVA_HOME/jre`).

**Comment by 0xilly** [comment]
> The reason I mention JAVA_HOME (or sometimes JRE_HOME) is because I personally don't have administrator access on my mac, so the version of java is rarely updated

The wrapper is built for this exact use case I think its out of scope for the wrapper to check for custom/nonstandard JRE installs.

**Comment by vandench** [comment]
I don't know `Go` personally but you could try `os.Getenv("JAVA_HOME")`.

**Comment by 0xilly** [comment]
I know the solution I'm just debating if another check is necessary. I'll think about it, I think its out of scope for the wrapper to support but its simple enough to add and forget.

**Comment by 0xilly** [comment]
After some thought I decided against adding this I think its out of scope to look for anything besides the default java install. I **might** add a argument for custom JRE's(though this might already be accomplished with a launcher.json argument) but that might be out of scope as well.
